[package]
name = "axmm"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "ArceOS virtual memory management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axmm"
documentation = "https://arceos-org.github.io/arceos/axmm/index.html"

[features]
default = []
copy = ["page_table/copy-from"]

[dependencies]
kalloc = { workspace = true }
platconfig = { workspace = true }
axerrno = { workspace = true }
axfs = { workspace = true }
axfs-ng-vfs = { workspace = true }
axhal = { workspace = true, features = ["paging"] }
axsync = { workspace = true }
axtask = { workspace = true }
enum_dispatch = { workspace = true }
kspin = { workspace = true }
lazyinit = { workspace = true }
log = { workspace = true }
memaddr = { workspace = true }
memset = { workspace = true }
page_table = { workspace = true, optional = true }
