[package]
name = "axmm"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Virtual memory management module"
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
default = []
copy = ["page_table/copy-from"]

[dependencies]
kalloc = { workspace = true }
platconfig = { workspace = true }
axerrno = { workspace = true }
kfs = { workspace = true }
fs-ng-vfs = { workspace = true }
khal = { workspace = true, features = ["paging"] }
ksync = { workspace = true }
ktask = { workspace = true }
enum_dispatch = { workspace = true }
kspin = { workspace = true }
lazyinit = { workspace = true }
log = { workspace = true }
memaddr = { workspace = true }
memset = { workspace = true }
page_table = { workspace = true, optional = true }
