[package]
name = "riscv64-qemu-virt"
version = "0.3.0"
description = "Implementation of `kplat` hardware abstraction layer for QEMU RISC-V virt board."
documentation = "https://docs.rs/kplat-riscv64-qemu-virt"
keywords = ["arceos", "os", "hal", "embedded", "riscv"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
fp-simd = ["kcpu/fp-simd"]
rtc = ["dep:riscv_goldfish"]
smp = ["kplat/smp"]

[dependencies]
kspin = { workspace = true }
lazyinit = "0.2"
log = "0.4"
riscv = "0.14"
riscv_goldfish = { version = "0.1", optional = true }
riscv_plic = { version = "0.2", optional = true }
sbi-rt = { version = "0.0.3", features = ["legacy"] }
uart_16550 = "0.4.0"

percpu = { workspace = true }
platconfig-macros = { workspace = true }
kcpu = { workspace = true }
kplat = { workspace = true }

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]
