[package]
name = "loongarch64-qemu-virt"
version = "0.3.0"
description = "Implementation of `kplat` hardware abstraction layer for QEMU LoongArch virtual machine."
documentation = "https://docs.rs/kplat-loongarch64-qemu-virt"
keywords = ["arceos", "os", "hal", "embedded", "loongarch"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
fp-simd = ["kcpu/fp-simd"]
irq = ["kplat/irq"]
rtc = ["dep:chrono"]
smp = ["kplat/smp", "kspin/smp"]

[dependencies]
chrono = { version = "0.4", default-features = false, optional = true }
kspin = { workspace = true }
lazyinit = "0.2"
log = "0.4"
loongArch64 = "0.2.4"
page_table = { workspace = true }
uart_16550 = "0.4.0"

platconfig-macros = { workspace = true }
kcpu = { workspace = true }
kplat = { workspace = true }

[package.metadata.docs.rs]
targets = ["loongarch64-unknown-none"]
