[package]
name = "aarch64-crosvm-virt"
description = "Implementation of `kplat` hardware abstraction layer for CROSVM ARM64 virtual machine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
fp-simd = ["kcpu/fp-simd"]
smp = ["kplat/smp"]
rtc = []

[dependencies]
log = "0.4"
page_table = { workspace = true }
platconfig-macros = { workspace = true }
kspin = "0.1"
dw_apb_uart = "0.1"
kcpu = { workspace = true }
kplat = { workspace = true }
aarch64-peripherals = { workspace = true, default-features = false, features = ["gicv3"] }
aarch64-cpu = "10.0"
rs_fdtree = { workspace = true }
spin = "0.9"
lazyinit = "0.2"
arm-gic.workspace = true

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
