[package]
name = "fbdevice"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ksync.workspace = true
kdriver = { workspace = true, features = ["display"] }
lazyinit.workspace = true
log.workspace = true
