[package]
name = "fbdevice"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
axdriver = { workspace = true, features = ["display"] }
ksync.workspace = true
lazyinit.workspace = true
log.workspace = true
