[package]
name = "axwatchdog"
version = "0.1.0"
edition = "2024"
authors = ["ZhiXian Luo <luozhixian@kylinos.cn>"]
license = "Apache-2.0"
description = "Watchdog timer with NMI support for embedded systems"
keywords = ["watchdog", "nmi", "embedded", "no_std"]
categories = ["no-std", "embedded", "hardware-support"]

[features]
default = ["khal/nmi"]

[dependencies]
platconfig.workspace = true
khal.workspace = true
ktask = { workspace = true, features = ["watchdog"] }
cfg-if.workspace = true
log.workspace = true
percpu.workspace = true
lazyinit.workspace = true
kspin.workspace = true
backtrace.workspace = true
ksync = { workspace = true, features = ["watchdog"] }
kplat.workspace = true
