[package]
name = "aarch64-qemu-virt"
description = "Implementation of `kplat` hardware abstraction layer for QEMU ARM64 virtual machine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
FP_SIMD = ["kcpu/fp-simd"]
SMP = ["kplat/smp"]
nmi = ["aarch64-peripherals/nmi-pmu", "kplat/nmi", "pmu"]
pmu = ["kplat/pmu"]

[dependencies]
log = "0.4"
page_table = { workspace = true }
aarch64-peripherals = { workspace = true, default-features = false, features = ["gicv2"]}
kcpu = { workspace = true }
kplat = { workspace = true }
kbuild_config = { workspace = true }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]

[package.metadata.kbuild]
enabled = true
