[package]
name = "aarch64-qemu-virt"
version = "0.3.0"
description = "Implementation of `kplat` hardware abstraction layer for QEMU ARM64 virtual machine."
documentation = "https://docs.rs/kplat-aarch64-qemu-virt"
keywords = ["arceos", "os", "hal", "embedded", "aarch64"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
fp-simd = ["kcpu/fp-simd"]
irq = ["kplat/irq", "aarch64-peripherals/irq"]
rtc = []
smp = ["kplat/smp"]
nmi = ["aarch64-peripherals/nmi-pmu", "kplat/nmi", "pmu"]
pmu = ["irq", "kplat/pmu"]

[dependencies]
log = "0.4"
page_table = { workspace = true }
platconfig-macros = { workspace = true }
aarch64-peripherals = { workspace = true, default-features = false, features = ["gicv2"]}
kcpu = { workspace = true }
kplat = { workspace = true }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
