[package]
name = "crate_rootfs"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "X TeeOS Crate Rootfs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rsext4 = { workspace = true, default-features = false }
