[package]
name = "kalloc"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[features]
tee = []
dice = []
default = ["tlsf", "alloc-engine/page-alloc-256m"]
tlsf = ["alloc-engine/tlsf"]
slab = ["alloc-engine/slab"]
buddy = ["alloc-engine/buddy"]
page-alloc-64g = [
    "alloc-engine/page-alloc-64g",
] # Support up to 64G memory capacity
page-alloc-4g = [
    "alloc-engine/page-alloc-4g",
] # Support up to 4G memory capacity
level-1 = []
tracking = ["dep:percpu", "dep:backtrace"]

[dependencies]
alloc-engine = { workspace = true, features = ["bitmap"] }
backtrace = { workspace = true, optional = true }
kerrno.workspace = true
cfg-if.workspace = true
kspin.workspace = true
log.workspace = true
memaddr.workspace = true
percpu = { workspace = true, optional = true }
strum = { workspace = true }
unittest.workspace = true
