[package]
name = "x86-pc"
description = "Implementation of `kplat` hardware abstraction layer for x86 Standard PC machine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
fp-simd = ["kcpu/fp-simd"]
rtc = ["x86_rtc"]
smp = ["kplat/smp", "kspin/smp"]
reboot-on-system-off = []

[dependencies]
kspin = { workspace = true }
log = "0.4"
bitflags = "2.6"
lazyinit = "0.2"
int_ratio = "0.1"
percpu = { workspace = true }
heapless = "0.9"
platconfig-macros = { workspace = true }
kcpu = { workspace = true }
kplat = { workspace = true }

x86 = "0.52"
x86_64 = "0.15.2"
x2apic = "0.5"
multiboot = "0.8"
raw-cpuid = "11.5"
uart_16550 = "0.4"
x86_rtc = { version = "0.1", optional = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-none"]
