[package]
name = "inputdev"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
kdriver = { workspace = true, features = ["input"] }
ksync.workspace = true
lazyinit.workspace = true
log.workspace = true
