[package]
name = "kdma"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
sev = []

[dependencies]
alloc-engine.workspace = true
kalloc.workspace = true
kerrno.workspace = true
khal = { workspace = true, features = ["paging"] }
crate_interface.workspace = true
kspin.workspace = true
log.workspace = true
memaddr.workspace = true
