[package]
name = "aarch64-peripherals"
description = "ARM64 common peripheral drivers with `kplat` compatibility"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
gicv2 = []
gicv3 = []
pmr = []
pmu = ["dep:aarch64-pmuv3", "kplat/pmu"]
nmi-pmu = ["pmr", "pmu", "kplat/nmi"]
nmi-sdei = []

[dependencies]
kspin = { workspace = true }
log = "0.4"
int_ratio = "0.1"
lazyinit = "0.2"
page_table = { workspace = true }
aarch64-cpu = "10.0"
arm_pl011 = "0.1"
arm-gic-driver = "0.15"
uart_16550 = "0.4"
arm_pl031 = "0.2"
kcpu = { workspace = true }
kplat = { workspace = true }
aarch64-pmuv3 = { workspace = true, optional = true }
percpu = { workspace = true }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
