[package]
name = "kspin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["synchronization", "spinlock", "no-irq"]
description = "Spinlocks used for kernel space that can disable preemption or IRQs in the critical section."
categories = ["os", "no-std"]

[features]
preempt = []
smp = []
default = []

[dependencies]
cfg-if = { workspace = true }
crate_interface = {workspace = true}
