[package]
name = "kconfig-gen"
description = "A TOML-based configuration generation tool for ArceOS."
documentation.workspace = true
categories = ["config", "parsing", "parser-implementations"]
keywords.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
toml_edit = { version = "0.22" }
clap = { version = "4", features = ["derive"] }
